Parameters: 

    Name:
        Description: An new enviroment Lead Solutions Architect
        Type: String

    

Resources:

  EC2Test:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-083654bd07b5da81d
      InstanceType: t2.micro	
      BlockDeviceMappings:
      - DeviceName: "/dev/sdk"
        Ebs:
          VolumeSize: '10'
      NetworkInterfaces: 
        - AssociatePublicIpAddress: "true"
          DeviceIndex: '0'
          SubnetId: subnet-00b43c3239928ed73
          GroupSet:
          - !Ref SGBastion
      KeyName: AWS_EC2_Demo	
      Tags: 
        - Key: Name 
          Value: !Sub ${Name}

  SGBastion:
        Type: AWS::EC2::SecurityGroup
        Properties:
          GroupDescription: Allow SSH to our hosts 
          VpcId: vpc-0ff98a8703f1a5ca7
          SecurityGroupIngress:
          - IpProtocol: tcp
            FromPort: 22
            ToPort: 22
            CidrIp: 0.0.0.0/0
          SecurityGroupEgress:
          - IpProtocol: -1
            CidrIp: 0.0.0.0/0
          Tags: 
            - Key: Name 
              Value: !Sub ${Name}-Security-Group